<?xml version="1.0"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd" [
    <!ELEMENT coverage (sources?, packages)>
    <!ATTLIST coverage line-rate CDATA #REQUIRED>
    <!ATTLIST coverage branch-rate CDATA #REQUIRED>
    <!ATTLIST coverage lines-covered CDATA #REQUIRED>
    <!ATTLIST coverage lines-valid CDATA #REQUIRED>
    <!ATTLIST coverage branches-covered CDATA #REQUIRED>
    <!ATTLIST coverage branches-valid CDATA #REQUIRED>
    <!ATTLIST coverage complexity CDATA #REQUIRED>
    <!ATTLIST coverage version CDATA #REQUIRED>
    <!ATTLIST coverage timestamp CDATA #REQUIRED>
    <!ELEMENT sources (source)*>
    <!ELEMENT source (#PCDATA)>
    <!ELEMENT packages (package)*>
    <!ELEMENT package (classes)>
    <!ATTLIST package name CDATA #REQUIRED>
    <!ATTLIST package line-rate CDATA #REQUIRED>
    <!ATTLIST package branch-rate CDATA #REQUIRED>
    <!ATTLIST package complexity CDATA #REQUIRED>
    <!ELEMENT classes (class)*>
    <!ELEMENT class (methods, lines)>
    <!ATTLIST class name CDATA #REQUIRED>
    <!ATTLIST class filename CDATA #REQUIRED>
    <!ATTLIST class line-rate CDATA #REQUIRED>
    <!ATTLIST class branch-rate CDATA #REQUIRED>
    <!ATTLIST class complexity CDATA #REQUIRED>
    <!ELEMENT methods (method)*>
    <!ELEMENT method (lines)>
    <!ATTLIST method name CDATA #REQUIRED>
    <!ATTLIST method signature CDATA #REQUIRED>
    <!ATTLIST method line-rate CDATA #REQUIRED>
    <!ATTLIST method branch-rate CDATA #REQUIRED>
    <!ATTLIST method complexity CDATA #REQUIRED>
    <!ELEMENT lines (line)*>
    <!ELEMENT line (conditions)*>
    <!ATTLIST line number CDATA #REQUIRED>
    <!ATTLIST line hits CDATA #REQUIRED>
    <!ATTLIST line branch CDATA "false">
    <!ELEMENT conditions (condition)*>
    <!ELEMENT condition EMPTY>
    <!ATTLIST condition number CDATA #REQUIRED>
    <!ATTLIST condition type CDATA #REQUIRED>
    <!ATTLIST condition coverage CDATA #REQUIRED>
]>

<coverage line-rate="0.8564356435643564" branch-rate="1.0" lines-covered="173" lines-valid="202" timestamp="1570055441.065824" version="diff_coverage 0.1" complexity="0.0" branches-valid="1.0" branches-covered="1.0">
    <sources>
        <source>/Users/febg/Library/Developer/Xcode/DerivedData/standard-swift-dypbnnfvsptvfhfthdefocijplag/Logs/Test</source>
    </sources>
    <packages>
        <package name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swiftUITests" line-rate="1.0" branch-rate="1.0" complexity="0.0">
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swiftUITests.standard_swiftUITests" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swiftUITests/standard_swiftUITests.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="13" branch="false" hits="1"/>
                    <line number="14" branch="false" hits="1"/>
                    <line number="15" branch="false" hits="1"/>
                    <line number="16" branch="false" hits="1"/>
                    <line number="17" branch="false" hits="1"/>
                    <line number="18" branch="false" hits="1"/>
                    <line number="19" branch="false" hits="1"/>
                    <line number="20" branch="false" hits="1"/>
                    <line number="21" branch="false" hits="1"/>
                    <line number="22" branch="false" hits="1"/>
                    <line number="23" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="27" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="1"/>
                    <line number="31" branch="false" hits="1"/>
                    <line number="32" branch="false" hits="1"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swiftUITests.Test_Index_UI" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swiftUITests/Test_Index_UI.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="14" branch="false" hits="2"/>
                    <line number="15" branch="false" hits="2"/>
                    <line number="16" branch="false" hits="2"/>
                    <line number="17" branch="false" hits="2"/>
                    <line number="18" branch="false" hits="2"/>
                    <line number="21" branch="false" hits="1"/>
                    <line number="22" branch="false" hits="1"/>
                    <line number="23" branch="false" hits="1"/>
                    <line number="24" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="1"/>
                    <line number="31" branch="false" hits="1"/>
                    <line number="32" branch="false" hits="1"/>
                    <line number="33" branch="false" hits="1"/>
                    <line number="34" branch="false" hits="1"/>
                    <line number="35" branch="false" hits="1"/>
                    <line number="33" branch="false" hits="1"/>
                    <line number="33" branch="false" hits="1"/>
                </lines>
            </class>
        </package>
        <package name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swiftTests" line-rate="1.0" branch-rate="1.0" complexity="0.0">
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swiftTests.standard_swiftTests" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swiftTests/standard_swiftTests.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="14" branch="false" hits="2"/>
                    <line number="15" branch="false" hits="2"/>
                    <line number="16" branch="false" hits="2"/>
                    <line number="18" branch="false" hits="2"/>
                    <line number="19" branch="false" hits="2"/>
                    <line number="20" branch="false" hits="2"/>
                    <line number="22" branch="false" hits="1"/>
                    <line number="23" branch="false" hits="1"/>
                    <line number="24" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="27" branch="false" hits="1"/>
                    <line number="28" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="1"/>
                    <line number="31" branch="false" hits="1"/>
                    <line number="32" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="10"/>
                    <line number="30" branch="false" hits="10"/>
                    <line number="31" branch="false" hits="10"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swiftTests.Test_Index" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swiftTests/Test_Index.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="18" branch="false" hits="2"/>
                    <line number="19" branch="false" hits="2"/>
                    <line number="20" branch="false" hits="2"/>
                    <line number="21" branch="false" hits="2"/>
                    <line number="22" branch="false" hits="2"/>
                    <line number="23" branch="false" hits="2"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="27" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="29" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="1"/>
                    <line number="31" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="1"/>
                </lines>
            </class>
        </package>
        <package name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift" line-rate="0.5833333333333334" branch-rate="1.0" complexity="0.0">
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift.SceneDelegate" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swift/SceneDelegate.swift" line-rate="0.5833333333333334" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="17" branch="false" hits="4"/>
                    <line number="18" branch="false" hits="4"/>
                    <line number="19" branch="false" hits="4"/>
                    <line number="20" branch="false" hits="4"/>
                    <line number="21" branch="false" hits="4"/>
                    <line number="22" branch="false" hits="4"/>
                    <line number="23" branch="false" hits="4"/>
                    <line number="24" branch="false" hits="4"/>
                    <line number="25" branch="false" hits="4"/>
                    <line number="26" branch="false" hits="4"/>
                    <line number="27" branch="false" hits="4"/>
                    <line number="28" branch="false" hits="4"/>
                    <line number="29" branch="false" hits="4"/>
                    <line number="31" branch="false" hits="0"/>
                    <line number="32" branch="false" hits="0"/>
                    <line number="33" branch="false" hits="0"/>
                    <line number="34" branch="false" hits="0"/>
                    <line number="35" branch="false" hits="0"/>
                    <line number="36" branch="false" hits="0"/>
                    <line number="38" branch="false" hits="4"/>
                    <line number="39" branch="false" hits="4"/>
                    <line number="40" branch="false" hits="4"/>
                    <line number="41" branch="false" hits="4"/>
                    <line number="43" branch="false" hits="0"/>
                    <line number="44" branch="false" hits="0"/>
                    <line number="45" branch="false" hits="0"/>
                    <line number="46" branch="false" hits="0"/>
                    <line number="48" branch="false" hits="4"/>
                    <line number="49" branch="false" hits="4"/>
                    <line number="50" branch="false" hits="4"/>
                    <line number="51" branch="false" hits="4"/>
                    <line number="53" branch="false" hits="0"/>
                    <line number="54" branch="false" hits="0"/>
                    <line number="55" branch="false" hits="0"/>
                    <line number="56" branch="false" hits="0"/>
                    <line number="57" branch="false" hits="0"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift.Index" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swift/Index.swift" line-rate="0.7333333333333333" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="14" branch="false" hits="1"/>
                    <line number="15" branch="false" hits="1"/>
                    <line number="16" branch="false" hits="1"/>
                    <line number="17" branch="false" hits="1"/>
                    <line number="18" branch="false" hits="1"/>
                    <line number="19" branch="false" hits="1"/>
                    <line number="20" branch="false" hits="1"/>
                    <line number="21" branch="false" hits="1"/>
                    <line number="22" branch="false" hits="0"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="26" branch="false" hits="1"/>
                    <line number="27" branch="false" hits="1"/>
                    <line number="30" branch="false" hits="0"/>
                    <line number="31" branch="false" hits="0"/>
                    <line number="32" branch="false" hits="0"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift.ContentView" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swift/ContentView.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="12" branch="false" hits="4"/>
                    <line number="13" branch="false" hits="4"/>
                    <line number="14" branch="false" hits="4"/>
                    <line number="15" branch="false" hits="4"/>
                    <line number="16" branch="false" hits="4"/>
                    <line number="17" branch="false" hits="4"/>
                    <line number="18" branch="false" hits="4"/>
                    <line number="19" branch="false" hits="4"/>
                    <line number="20" branch="false" hits="4"/>
                    <line number="21" branch="false" hits="4"/>
                    <line number="22" branch="false" hits="4"/>
                    <line number="14" branch="false" hits="4"/>
                    <line number="15" branch="false" hits="4"/>
                    <line number="16" branch="false" hits="4"/>
                    <line number="17" branch="false" hits="4"/>
                    <line number="18" branch="false" hits="4"/>
                    <line number="19" branch="false" hits="4"/>
                    <line number="20" branch="false" hits="4"/>
                    <line number="21" branch="false" hits="4"/>
                    <line number="15" branch="false" hits="20"/>
                    <line number="16" branch="false" hits="20"/>
                    <line number="17" branch="false" hits="20"/>
                    <line number="18" branch="false" hits="20"/>
                    <line number="19" branch="false" hits="20"/>
                    <line number="16" branch="false" hits="20"/>
                    <line number="17" branch="false" hits="20"/>
                    <line number="18" branch="false" hits="20"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift.ContentRow" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swift/ContentRow.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="16" branch="false" hits="20"/>
                    <line number="17" branch="false" hits="20"/>
                    <line number="18" branch="false" hits="20"/>
                    <line number="19" branch="false" hits="20"/>
                    <line number="20" branch="false" hits="20"/>
                    <line number="21" branch="false" hits="20"/>
                    <line number="22" branch="false" hits="20"/>
                    <line number="23" branch="false" hits="20"/>
                    <line number="24" branch="false" hits="20"/>
                    <line number="25" branch="false" hits="20"/>
                    <line number="26" branch="false" hits="20"/>
                    <line number="17" branch="false" hits="20"/>
                    <line number="18" branch="false" hits="20"/>
                    <line number="19" branch="false" hits="20"/>
                    <line number="20" branch="false" hits="20"/>
                    <line number="21" branch="false" hits="20"/>
                    <line number="22" branch="false" hits="20"/>
                    <line number="23" branch="false" hits="20"/>
                    <line number="24" branch="false" hits="20"/>
                    <line number="20" branch="false" hits="20"/>
                    <line number="21" branch="false" hits="20"/>
                    <line number="22" branch="false" hits="20"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift.ContentDetail" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swift/ContentDetail.swift" line-rate="1.0" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="16" branch="false" hits="1"/>
                    <line number="17" branch="false" hits="1"/>
                    <line number="18" branch="false" hits="1"/>
                    <line number="19" branch="false" hits="1"/>
                    <line number="20" branch="false" hits="1"/>
                    <line number="21" branch="false" hits="1"/>
                    <line number="22" branch="false" hits="1"/>
                    <line number="23" branch="false" hits="1"/>
                    <line number="24" branch="false" hits="1"/>
                    <line number="25" branch="false" hits="1"/>
                    <line number="17" branch="false" hits="1"/>
                    <line number="18" branch="false" hits="1"/>
                    <line number="19" branch="false" hits="1"/>
                    <line number="20" branch="false" hits="1"/>
                    <line number="21" branch="false" hits="1"/>
                </lines>
            </class>
            <class name="Users.febg.Documents.Work.CodeCov.swift-standard.standard-swift.AppDelegate" filename="/Users/febg/Documents/Work/CodeCov/swift-standard/standard-swift/AppDelegate.swift" line-rate="0.2857142857142857" branch-rate="1.0" complexity="0.0">
                <lines>
                    <line number="16" branch="false" hits="4"/>
                    <line number="17" branch="false" hits="4"/>
                    <line number="18" branch="false" hits="4"/>
                    <line number="19" branch="false" hits="4"/>
                    <line number="23" branch="false" hits="0"/>
                    <line number="24" branch="false" hits="0"/>
                    <line number="25" branch="false" hits="0"/>
                    <line number="26" branch="false" hits="0"/>
                    <line number="27" branch="false" hits="0"/>
                    <line number="29" branch="false" hits="0"/>
                    <line number="30" branch="false" hits="0"/>
                    <line number="31" branch="false" hits="0"/>
                    <line number="32" branch="false" hits="0"/>
                    <line number="33" branch="false" hits="0"/>
                </lines>
            </class>
        </package>
    </packages>
</coverage>
